doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/User'
                prefix: 'App\Domain\User'
                alias: User
            Task:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Task'
                prefix: 'App\Domain\Task'
                alias: Task
        controller_resolver:
            auto_mapping: false
