# framework:
#     messenger:
#         default_bus: command.bus
#         buses:
#             event.bus: ~  
#             command.bus: ~
#         transports:
#             async: 
#                 dsn: 'doctrine://default' 
#         routing:
#             App\Domain\Task\Event\TaskCreatedEvent: async 