controllers:
    resource:
        path: ../src/Application/Controller/
        namespace: App\Application\Controller
    type: attribute

api_users:
    resource: '../src/Application/Controller/UserController.php'
    type: attribute

