controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
api_users:
    resource: '../src/Controller/UserController.php'
    type: attribute

api_tasks:
    resource: '../src/Controller/TaskController.php'
    type: attribute